[package]
name = "wasm-tests"
version = "0.0.0"
edition = { workspace = true }
publish = false

[lib]
crate-type = ['cdylib']

[dev-dependencies]
webassembly-test = "0.1"
getrandom = { version = "0.2", features = ["js"] }
fuels-types = { path = "../fuels-types" }
fuels-macros = { workspace = true }
fuels-core = { workspace = true }